Repository scikit-hep/decaylanguage, pull requests merged in 2022-11, with the labels that each got.

#273 docs: add package contributors
  README.md
Labels: doc

#270 ModelAlias support and update of Belle II Decayfile
  .github/workflows/ci.yml
  src/decaylanguage/data/DECAY_BELLE2.DEC
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  src/decaylanguage/dec/enums.py
  src/decaylanguage/decay/decay.py
  tests/data/defs-aliases-chargeconj.dec
  tests/data/test_DtoKlnu.dec
  tests/data/test_Upsilon2S2UpsilonPiPi.dec
  tests/dec/test_dec.py
Labels: enhancement

#282 Adapt to Python 3 only Lark 1.x
  README.md
  environment.yml
  notebooks/ExampleDecFileParsingWithLark.ipynb
  pyproject.toml
  src/decaylanguage/data/WorkingOutModel.ipynb
  src/decaylanguage/dec/dec.py
  tests/test_dec_full.py
Labels: enhancement, dependencies

#283 chore: Prepare release 0.15.0
  CHANGELOG.md
  environment.yml
  pyproject.toml
Labels: release
