Repository scikit-hep/decaylanguage, pull requests merged in 2023-07, with the labels that each got.

#341 fix mass combinations in generated GooFit code
  src/decaylanguage/modeling/goofit.py
  tests/output/DtoKpipipi_v2.cu
Labels: enhancement

#348 Start adding get methods and tests for recently added EvtGen keywords
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  tests/data/defs-aliases-chargeconj.dec
  tests/dec/test_dec.py
Labels: enhancement, tests

#350 Prepare release 0.15.5
  CHANGELOG.md
Labels: release

#352 Add latest LHCb master DECAY.DEC file
  src/decaylanguage/data/DECAY_LHCB.DEC
  tests/dec/test_dec.py
Labels: enhancement

#351 Simplify the decay file parsing grammar and implement more get methods for EvtGen keywords + unit tests
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  tests/dec/test_dec.py
Labels: enhancement

#353 Allow dec file Decay statements to effectively be able to set a particle as stable
  src/decaylanguage/data/decfile.lark
  tests/data/minimalistic.dec
  tests/data/test_stable-particle.dec
  tests/dec/test_dec.py
Labels: enhancement

#354 Further simplify the decay file parsing grammar and implement more get methods for EvtGen keywords + unit tests
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  tests/data/defs-aliases-chargeconj.dec
  tests/dec/test_dec.py
Labels: enhancement

#358 Prepare for release 0.16.0
  CHANGELOG.md
Labels: release
