Repository scikit-hep/decaylanguage, pull requests merged in 2023-11, with the labels that each got.

#388 Update ci.yml to pin Python to 3.11 in pre-commit checks while pylcn gets fixed for 3.12
  .github/workflows/ci.yml
Labels: ci

#387 Test suite to verify all EvtGen models are parsed correctly - take 6
  tests/data/models/model-BQTOLLLL.dec
  tests/data/models/model-BQTOLLLLHYPERCP.dec
  tests/data/models/model-BTOSLLALI.dec
  tests/data/models/model-BTOSLLBALL.dec
  tests/data/models/model-BTOSLLMS.dec
  tests/data/models/model-BTOSLLMSEXT.dec
  tests/data/models/model-BTOVLNUBALL.dec
  tests/data/models/model-CB3PI-MPP.dec
  tests/data/models/model-CB3PI-P00.dec
  tests/data/models/model-ETA_LLPIPI.dec
  tests/data/models/model-FLATQ2.dec
  tests/data/models/model-FOURBODYPHSP.dec
  tests/data/models/model-HELAMP.dec
  tests/data/models/model-PTO3P.dec
  tests/dec/test_known_decay_models.py
Labels: tests

#389 Fix LHCb model name - take 2
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/enums.py
  tests/dec/test_known_decay_models.py
Labels: fix

#385 Refactored grammar to remove need for second transformer
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  tests/dec/test_dec.py
  tests/dec/test_known_decay_models.py
Labels: enhancement

#393 Update pylcn to 2.4.0 that supports Python 3.12
  .github/workflows/ci.yml
  .pre-commit-config.yaml
Labels: ci

#391 Test suite to verify all EvtGen models are parsed correctly - take 7
  tests/data/models/model-HQET.dec
  tests/data/models/model-ISGW2.dec
  tests/data/models/model-KS_PI0MUMU.dec
  tests/data/models/model-Lb2Baryonlnu.dec
  tests/data/models/model-Lb2plnuLCSR.dec
  tests/data/models/model-Lb2plnuLQCD.dec
  tests/data/models/model-LbAmpGen.dec
  tests/data/models/model-PHSPDECAYTIMECUT.dec
  tests/data/models/model-PHSPFLATLIFETIME.dec
  tests/data/models/model-PVV_CPLH.dec
  tests/data/models/model-PYCONT.dec
  tests/data/models/model-SLL.dec
  tests/data/models/model-SLN.dec
  tests/data/models/model-SSD_DirectCP.dec
  tests/data/models/model-SSS_CP.dec
  tests/data/models/model-STS.dec
  tests/data/models/model-SVP.dec
  tests/data/models/model-SVP_HELAMP.dec
  tests/data/models/model-SVS.dec
  tests/data/models/model-SVS_CP.dec
  tests/data/models/model-SVS_NONCPEIGEN.dec
  tests/data/models/model-SVV_CP.dec
  tests/data/models/model-SVV_HELAMP.dec
  tests/data/models/model-TAUOLA.dec
  tests/data/models/model-TVP.dec
  tests/data/models/model-TVS_PWAVE.dec
  tests/data/models/model-VTOSLL.dec
  tests/data/models/model-VUB.dec
  tests/data/models/model-VVP.dec
  tests/data/models/model-VVPIPI.dec
  tests/data/models/model-VVS_PWAVE.dec
  tests/data/models/model-XLL.dec
  tests/dec/test_known_decay_models.py
Labels: enhancement, tests

#394 Test suite to verify all EvtGen models are parsed correctly - take 8
  tests/data/models/model-ISGW.dec
  tests/data/models/model-MELIKHOV.dec
  tests/data/models/model-PROPSLPOLE.dec
  tests/data/models/model-SLBKPOLE.dec
  tests/data/models/model-SLPOLE.dec
  tests/data/models/model-SSS_CPT.dec
  tests/data/models/model-SSS_CP_PNG.dec
  tests/data/models/model-STS_CP.dec
  tests/data/models/model-SVP_CP.dec
  tests/data/models/model-SVS_CPLH.dec
  tests/data/models/model-SVVHELCPMIX.dec
  tests/data/models/model-SVV_CPLH.dec
  tests/data/models/model-SVV_NONCPEIGEN.dec
  tests/data/models/model-VSS_MIX.dec
  tests/dec/test_known_decay_models.py
Labels: enhancement, tests

#395 chore: modernize Ruff config
  pyproject.toml
Labels: enhancement, ci

#396 Several EvtGen model enhancements and a fix
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/dec.py
  src/decaylanguage/dec/enums.py
  tests/data/models/model-BT02PI_CP_ISO.dec
  tests/data/models/model-BTOXELNU.dec
  tests/data/models/model-GENERIC_DALITZ.dec
  tests/data/models/model-RareLbToLll.dec
  tests/data/models/model-SVS_CP_ISO.dec
  tests/dec/test_known_decay_models.py
Labels: enhancement, tests, fix

#397 Add new models found in the EvtGen manual
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/enums.py
  tests/data/models/model-B_TO_2BARYON_SCALAR.dec
  tests/data/models/model-B_TO_LAMBDA_PBAR_GAMMA.dec
  tests/dec/test_known_decay_models.py
Labels: enhancement

#398 chore: use Self
  .pre-commit-config.yaml
  src/decaylanguage/_compat/__init__.py
  src/decaylanguage/_compat/typing.py
  src/decaylanguage/dec/dec.py
  src/decaylanguage/decay/decay.py
Labels: enhancement, ci

#400 fix: support passing though dm, nicer typing
  .pre-commit-config.yaml
  src/decaylanguage/dec/dec.py
  src/decaylanguage/decay/decay.py
  tests/dec/test_dec.py
Labels: enhancement

#401 Support all available Belle II decay models
  src/decaylanguage/data/decfile.lark
  src/decaylanguage/dec/enums.py
  tests/data/models/model-BSTD.dec
  tests/data/models/model-BSTD_2HDMTYPE2.dec
  tests/data/models/model-BTOXSNUNU_FERMI.dec
  tests/data/models/model-KNUNU.dec
  tests/data/models/model-KSTARNUNU_REV.dec
  tests/data/models/model-PHSP_BB_MIX.dec
  tests/data/models/model-PHSP_B_MIX.dec
  tests/data/models/model-PHSP_CP.dec
  tests/data/models/model-VECTORISR.dec
  tests/data/models/model-VUB_BLNP.dec
  tests/dec/test_known_decay_models.py
Labels: enhancement
