Repository scikit-hep/decaylanguage, pull requests merged in 2024-08, with the labels that each got.

#452 Fixed bug in print_decay_modes where decays with equal BFs were skipped
  src/decaylanguage/dec/dec.py
  tests/dec/test_dec.py
  tests/output/DtoKpipipi_v2.cu
Labels: fix

#455 EvtGen uses GeV, not the standard HEP system of units, hence MeV!
  pyproject.toml
  src/decaylanguage/dec/dec.py
  tests/data/defs-aliases-chargeconj.dec
  tests/dec/test_dec.py
Labels: fix

#456 Remove deprecated method DecFileParser.load_grammar
  codecov.yml
  src/decaylanguage/dec/dec.py
Labels: chore

#457 Get Codecov to upload again
  .github/workflows/ci.yml
Labels: ci
